# Question 5.
Use Naive bayes, K-nearest, and Decision tree classification algorithms and build classifiers.
Divide the data set into training and test set. Compare the accuracy of the different classifiers
under the following situations:
5.1 a) Training set = 75% Test set = 25% b) Training set = 66.6% (2/3rd of total), Test set =
33.3%
5.2 Training set is chosen by i) hold out method ii) Random subsampling iii) Cross-Validation.
Compare the accuracy of the classifiers obtained.
5.3 Data is scaled to standard format.

In [38]:
import sklearn
import sklearn.naive_bayes
import sklearn.neighbors
import sklearn.tree
import sklearn.model_selection
import sklearn.datasets
import sklearn.metrics


In [44]:
data=sklearn.datasets.load_iris() 
X_train, X_test, y_train, y_test = sklearn.model_selection.train_test_split(data.data, data.target, test_size=0.33, random_state=42)

In [45]:
model1=sklearn.tree.DecisionTreeClassifier(random_state=0)

In [46]:
model2=sklearn.neighbors.KNeighborsClassifier(n_neighbors=3)

In [47]:
model3=sklearn.naive_bayes.GaussianNB()

In [48]:
model1.fit(X_train,y_train)
model2.fit(X_train,y_train)
model3.fit(X_train,y_train)


GaussianNB()

In [49]:
y_pre_1=model1.predict(X_test)
y_pre_2=model2.predict(X_test)
y_pre_3=model3.predict(X_test)

In [50]:
sklearn.metrics.accuracy_score(y_test, y_pre_1)

0.96

In [51]:
sklearn.metrics.accuracy_score(y_test, y_pre_2)

0.98

In [52]:
sklearn.metrics.accuracy_score(y_test, y_pre_3)

0.96

In [53]:
sklearn.metrics.confusion_matrix(y_test, y_pre_3)

array([[19,  0,  0],
       [ 0, 14,  1],
       [ 0,  1, 15]], dtype=int64)

In [54]:
print(sklearn.model_selection.cross_val_score(model1, data.data, data.target, cv=3))

[0.98 0.94 0.98]


In [55]:
print(sklearn.model_selection.cross_val_score(model2, data.data, data.target, cv=3))

[0.98 0.96 0.98]


In [56]:
print(sklearn.model_selection.cross_val_score(model3, data.data, data.target, cv=3))

[0.92 0.94 0.96]


In [43]:
help(sklearn.utils)

Help on package sklearn.utils in sklearn:

NAME
    sklearn.utils - The :mod:`sklearn.utils` module includes various utilities.

PACKAGE CONTENTS
    _arpack
    _cython_blas
    _encode
    _estimator_html_repr
    _fast_dict
    _joblib
    _logistic_sigmoid
    _mask
    _mocking
    _openmp_helpers
    _pprint
    _random
    _readonly_array_wrapper
    _seq_dataset
    _show_versions
    _tags
    _testing
    _typedefs
    _weight_vector
    arrayfuncs
    class_weight
    deprecation
    estimator_checks
    extmath
    fixes
    graph
    metaestimators
    multiclass
    murmurhash
    optimize
    random
    setup
    sparsefuncs
    sparsefuncs_fast
    stats
    tests (package)
    validation

CLASSES
    builtins.UserWarning(builtins.Warning)
        sklearn.exceptions.DataConversionWarning
    builtins.object
        joblib.parallel.parallel_backend
        sklearn.utils.deprecation.deprecated
    
    class DataConversionWarning(builtins.UserWarning)
     |  Warning used

In [24]:
help(sklearn.metrics)

Help on package sklearn.metrics in sklearn:

NAME
    sklearn.metrics

DESCRIPTION
    The :mod:`sklearn.metrics` module includes score functions, performance metrics
    and pairwise metrics and distance computations.

PACKAGE CONTENTS
    _base
    _classification
    _dist_metrics
    _pairwise_fast
    _plot (package)
    _ranking
    _regression
    _scorer
    cluster (package)
    pairwise
    setup
    tests (package)

CLASSES
    builtins.object
        sklearn.metrics._dist_metrics.DistanceMetric
        sklearn.metrics._plot.confusion_matrix.ConfusionMatrixDisplay
        sklearn.metrics._plot.det_curve.DetCurveDisplay
        sklearn.metrics._plot.precision_recall_curve.PrecisionRecallDisplay
        sklearn.metrics._plot.roc_curve.RocCurveDisplay
    
    class ConfusionMatrixDisplay(builtins.object)
     |  ConfusionMatrixDisplay(confusion_matrix, *, display_labels=None)
     |  
     |  Confusion Matrix visualization.
     |  
     |  It is recommend to use
     |  :func

In [14]:
help(sklearn.model_selection)

Help on package sklearn.model_selection in sklearn:

NAME
    sklearn.model_selection

PACKAGE CONTENTS
    _search
    _search_successive_halving
    _split
    _validation
    tests (package)

CLASSES
    builtins.object
        sklearn.model_selection._search.ParameterGrid
        sklearn.model_selection._search.ParameterSampler
        sklearn.model_selection._split.BaseCrossValidator
            sklearn.model_selection._split.LeaveOneGroupOut
            sklearn.model_selection._split.LeaveOneOut
            sklearn.model_selection._split.LeavePGroupsOut
            sklearn.model_selection._split.LeavePOut
            sklearn.model_selection._split.PredefinedSplit
        sklearn.model_selection._split.BaseShuffleSplit
            sklearn.model_selection._split.ShuffleSplit
                sklearn.model_selection._split.GroupShuffleSplit
            sklearn.model_selection._split.StratifiedShuffleSplit
    sklearn.model_selection._search.BaseSearchCV(sklearn.base.MetaEstimatorMixi

In [10]:
help(sklearn.naive_bayes)

Help on module sklearn.naive_bayes in sklearn:

NAME
    sklearn.naive_bayes

DESCRIPTION
    The :mod:`sklearn.naive_bayes` module implements Naive Bayes algorithms. These
    are supervised learning methods based on applying Bayes' theorem with strong
    (naive) feature independence assumptions.

CLASSES
    _BaseDiscreteNB(_BaseNB)
        BernoulliNB
        CategoricalNB
        ComplementNB
        MultinomialNB
    _BaseNB(sklearn.base.ClassifierMixin, sklearn.base.BaseEstimator)
        GaussianNB
    
    class BernoulliNB(_BaseDiscreteNB)
     |  BernoulliNB(*, alpha=1.0, binarize=0.0, fit_prior=True, class_prior=None)
     |  
     |  Naive Bayes classifier for multivariate Bernoulli models.
     |  
     |  Like MultinomialNB, this classifier is suitable for discrete data. The
     |  difference is that while MultinomialNB works with occurrence counts,
     |  BernoulliNB is designed for binary/boolean features.
     |  
     |  Read more in the :ref:`User Guide <bernoulli

In [8]:
help(sklearn.neighbors)

Help on package sklearn.neighbors in sklearn:

NAME
    sklearn.neighbors

DESCRIPTION
    The :mod:`sklearn.neighbors` module implements the k-nearest neighbors
    algorithm.

PACKAGE CONTENTS
    _ball_tree
    _base
    _classification
    _distance_metric
    _graph
    _kd_tree
    _kde
    _lof
    _nca
    _nearest_centroid
    _partition_nodes
    _quad_tree
    _regression
    _unsupervised
    setup
    tests (package)

CLASSES
    sklearn.base.BaseEstimator(builtins.object)
        sklearn.neighbors._kde.KernelDensity
        sklearn.neighbors._nca.NeighborhoodComponentsAnalysis(sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
        sklearn.neighbors._nearest_centroid.NearestCentroid(sklearn.base.ClassifierMixin, sklearn.base.BaseEstimator)
    sklearn.base.ClassifierMixin(builtins.object)
        sklearn.neighbors._classification.KNeighborsClassifier(sklearn.neighbors._base.KNeighborsMixin, sklearn.base.ClassifierMixin, sklearn.neighbors._base.NeighborsBase)
  

In [4]:
help(sklearn.tree)

Help on package sklearn.tree in sklearn:

NAME
    sklearn.tree

DESCRIPTION
    The :mod:`sklearn.tree` module includes decision tree-based models for
    classification and regression.

PACKAGE CONTENTS
    _classes
    _criterion
    _export
    _reingold_tilford
    _splitter
    _tree
    _utils
    setup
    tests (package)

CLASSES
    sklearn.base.BaseEstimator(builtins.object)
        sklearn.tree._classes.BaseDecisionTree(sklearn.base.MultiOutputMixin, sklearn.base.BaseEstimator)
            sklearn.tree._classes.DecisionTreeClassifier(sklearn.base.ClassifierMixin, sklearn.tree._classes.BaseDecisionTree)
                sklearn.tree._classes.ExtraTreeClassifier
            sklearn.tree._classes.DecisionTreeRegressor(sklearn.base.RegressorMixin, sklearn.tree._classes.BaseDecisionTree)
                sklearn.tree._classes.ExtraTreeRegressor
    sklearn.base.ClassifierMixin(builtins.object)
        sklearn.tree._classes.DecisionTreeClassifier(sklearn.base.ClassifierMixin, sklea

In [2]:
help(sklearn)

Help on package sklearn:

NAME
    sklearn

DESCRIPTION
    Machine learning module for Python
    
    sklearn is a Python module integrating classical machine
    learning algorithms in the tightly-knit world of scientific Python
    packages (numpy, scipy, matplotlib).
    
    It aims to provide simple and efficient solutions to learning problems
    that are accessible to everybody and reusable in various contexts:
    machine-learning as a versatile tool for science and engineering.
    
    See http://scikit-learn.org for complete documentation.

PACKAGE CONTENTS
    __check_build (package)
    _build_utils (package)
    _config
    _distributor_init
    _isotonic
    _loss (package)
    _min_dependencies
    base
    calibration
    cluster (package)
    compose (package)
    conftest
    covariance (package)
    cross_decomposition (package)
    datasets (package)
    decomposition (package)
    discriminant_analysis
    dummy
    ensemble (package)
    exceptions
    experime